# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push

jobs:
  hello-world:
    name: Hello World

    runs-on: ubuntu-20.04

    steps:
      - name: Hello
        run: |
          echo Hello
