# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push

jobs:
  hello-world:
    name: Hello World

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Cache the Repository
        uses: actions/cache@v2
        id: cache
        with:
          path: ./github
          key: ${{ runner.os }}-${{ hashFiles('./.github/*') }}-workflows

      - name: Display Cache Hit
        run: |
          echo ${{ steps.cache.outputs.cache-hit }}

      - name: List the Repository Contents
        run: |
          ls -la
