# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push

jobs:
  hello-world:
    name: Hello World

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        run: |
          git clone https://github.com/${{ github.event.repository.full_name }}

      - name: List the Repository Contents
        run: |
          ls -la
