# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push

jobs:
  hello-world:
    name: Hello World

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: List the Repository Contents
        run: |
          ls -la

  pancake:
    name: Pancake

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: List the Repository Contents
        run: |
          ls -la
