# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push

jobs:
  test:
    name: Test

    strategy:
      matrix:
        node: [12, 14, 16]
        platform: [ubuntu-20.04, ubuntu-18.04]
        exclude:
          - node: 12
            platform: ubuntu-18.04

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Test the Application
        run: |
          node index.js

  pancake:
    name: Pancake

    needs: [test]

    runs-on: ubuntu-18.04

    steps:
      - name: Ahoy
        run: |
          echo Ahoy
