# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push
- pull_request

jobs:
  hello-world:
    name: Hello World

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: List the Repository Contents
        run: |
          ls -la

  pancake:
    name: Pancake

    needs: [hello-world]

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: List the Repository Contents
        if: success() || failure()
        run: |
          ls -la

      - name: Upload the .github folder
        uses: actions/upload-artifact@v3
        with:
          name: dot-github-folder
          path: .github

  attack:
    name: Attack

    needs: [pancake]

    runs-on: ubuntu-20.04

    steps:
      - name: Download the .github folder
        uses: actions/download-artifact@v3
        with:
          name: dot-github-folder
          path: .github

      - name: List the Contents
        if: success() || failure()
        run: |
          ls -la