# Continuous Integration workflow documentation.
name: Continuous Integration

on:
- push

jobs:
  test:
    name: Test

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Test the Application
        run: |
          node index.js
